/**
 * Extracts only the brand icons this site uses from the Iconify collections
 * into a static local module.
 *
 * Why: `@iconify/react` resolves icons by fetching api.iconify.design at
 * runtime, which costs a third-party round trip per page and makes icons pop
 * in after hydration. Baking the handful we need into the bundle removes both,
 * and lets icons render on the server.
 *
 * Run with: npm run icons
 */
import { readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")

/** Icons referenced from lib/site-data.ts, as `collection:name`. */
const WANTED = [
  // Frontend
  "logos:react",
  "logos:nextjs-icon",
  "logos:typescript-icon",
  "logos:javascript",
  "logos:redux",
  "logos:react-query-icon",
  "logos:vitejs",
  "logos:testing-library",
  "logos:playwright",
  "logos:html-5",
  "logos:css-3",
  "logos:tailwindcss-icon",
  "logos:bootstrap",
  // Backend
  "logos:nodejs-icon",
  "logos:nestjs",
  "logos:laravel",
  "logos:mysql-icon",
  "logos:postgresql",
  "logos:prisma",
  "logos:php",
  // Tools
  "logos:git-icon",
  "logos:docker-icon",
  "logos:postman-icon",
  "logos:sentry-icon",
  "logos:visual-studio-code",
  "logos:claude-icon",
  "logos:openai-icon",
  // No `logos:cursor` in the collection; simple-icons is monochrome and
  // inherits currentColor, which is fine for a wordless mark.
  "simple-icons:cursor",
]

const collections = new Map()

async function loadCollection(name) {
  if (collections.has(name)) return collections.get(name)
  const raw = await readFile(resolve(root, "node_modules", `@iconify-json/${name}/icons.json`), "utf8")
  const parsed = JSON.parse(raw)
  collections.set(name, parsed)
  return parsed
}

/** Follows `aliases` until it lands on a concrete icon definition. */
function resolveIcon(collection, name, depth = 0) {
  if (depth > 5) return null
  if (collection.icons?.[name]) return collection.icons[name]
  const alias = collection.aliases?.[name]
  if (alias?.parent) return resolveIcon(collection, alias.parent, depth + 1)
  return null
}

const entries = []
const missing = []

for (const id of WANTED) {
  const [collectionName, iconName] = id.split(":")
  const collection = await loadCollection(collectionName)
  const icon = resolveIcon(collection, iconName)

  if (!icon) {
    missing.push(id)
    continue
  }

  entries.push({
    id,
    body: icon.body,
    width: icon.width ?? collection.width ?? 24,
    height: icon.height ?? collection.height ?? 24,
  })
}

if (missing.length) {
  console.error(`Missing icons:\n  ${missing.join("\n  ")}`)
  process.exitCode = 1
}

const file = `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Run \`npm run icons\` after changing the icon list in that script.

export interface TechIconData {
  body: string
  width: number
  height: number
}

export const techIcons: Record<string, TechIconData> = {
${entries
  .map((entry) => `  ${JSON.stringify(entry.id)}: ${JSON.stringify({ body: entry.body, width: entry.width, height: entry.height })},`)
  .join("\n")}
}
`

await mkdir(resolve(root, "lib/generated"), { recursive: true })
await writeFile(resolve(root, "lib/generated/tech-icons.ts"), file, "utf8")

console.log(`Wrote ${entries.length} icons to lib/generated/tech-icons.ts`)
